
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = [
    "matplotlib",
    "pandas",
    "numpy",
    "mplhep",
    "uproot",
    "black",
    "isort",
    "corner",
    # Requirements for NIFTy
    # "nifty8",
    # "ducc0",
    # "h5py",
    # "jax",
	# matplotlib removed function needed by pygtc (corner plot alternative), install 3.7.0 if you want
    # "pygtc",
]
name = "PyAmpTools"
requires-python = ">=3.7"
version = "0.0.0"

[tool.isort]
known_third_party = "THIRDPARTY,sympy"
profile = "black"

[tool.nbqa.addopts]
black = ["--line-length=85"]
